### ISSUE TITLE
Opening a specific HA URL?

### ISSUE THREAD

**Issue by upamanyudas** [kcsoft/virtual-keys#1]
Thanks for building this. Fount it while looking for guest access methods in HA. Love the overall concept and the massive workflow improvement. If it would redirect to the specific guest dashboard URL maybe with a ?kiosk flag after login, instead of the default lovelace, that will be a massive gain! Maybe an option for a custom url while generating the key? This in my view gives more control to the user.

**Comment by kcsoft** [comment]
Appreciate your comment.

In fact you can easily do that, I described that in the README file

> To make this work, I need to make some additional steps (after installing Virtual Keys):
> + create a new user in Home Assistant eg. "guest"
> + create a new group eg. "guests" and add the user "guest" to it, and also the devices you want to give access to, eg "cover.front_gate", instructions [here](https://developers.home-assistant.io/blog/2019/03/11/user-permissions/)
> + create a new View (tab) in the default Lovelace UI and add the entities you want to give access to, eg. "cover.front_gate", set the visibility to only show to user "guest".

install [kiosk-mode](https://github.com/NemesisRE/kiosk-mode) and configure it set "kiosk" mode for user "guest"


This is how it looks in my case where I have setup a View (tab) with only those 2 entities for my guest user:
![image](https://user-images.githubusercontent.com/176441/202801589-301dca42-3596-42b3-bf15-f42eb5f64d7a.png)

No special url but for this user the kiosk mode is on.

**Comment by upamanyudas** [comment]
Thanks for the reply.

I think the solution you mentioned only works if I don't have the automatic Lovelace dashboard and can control the visibility of individual View (tabs). The thing is I want to keep the default auto updating lovelace, but in that scenario - after logging in, even from the guest account, HA sends the user to the default lovelace.

I though if I could direct them to `/lovelace-guest/0` or any other page, instead of the default `/lovelace/0` - that'd let me have more control.

Hence the suggestion :)

**Comment by kcsoft** [comment]
If the guest has access to `/lovelace/0`, even if you redirect them to `/lovelace-guest/0`, they can still manually navigate to `/lovelace/0`.

If you need some special redirect, you can fork this repo and change it. Here is where the redirect url is determined.
https://github.com/kcsoft/virtual-keys/blob/master/dist/login.html#L5

**Comment by dakmalandro** [comment]
hello there!!! very nice work!!! i have followed all the steps in the read.me file, but i can't copy the url after create a log in

**Comment by kcsoft** [comment]
![image](https://user-images.githubusercontent.com/176441/211349918-68b846a3-fc5e-4f8f-b373-7acbcf14bc40.png)

**Comment by kcsoft** [comment]
closing as this was actually a support ticket
