### ISSUE TITLE
No copy code

### ISSUE THREAD

**Issue by ouranos6** [kcsoft/virtual-keys#2]
Hello, I've tried to use your add-on but it didn't give me a code... but instead I have this issue on the chrome debug console

<img width="1292" alt="image" src="https://user-images.githubusercontent.com/20718760/229042693-c4c0e2c0-2cfc-4710-a9eb-3106f3e51317.png">

Can you help me?

**Comment by kcsoft** [comment]
Yes, it looks like you have to serve the page from a secure domain (https). Or disable that in chrome flags.
See the accepted answer here: https://stackoverflow.com/questions/51805395/navigator-clipboard-is-undefined

**Comment by ouranos6** [comment]
Ok, I will check that on Monday. Is it possible to show the keys on the button when pressing it? This way it’s possible to use it without having an server with httpS

Another thing I would ask for is to have a calendar like for let say the arrival time and departure time this way we can automatically calculate how many minutes are staying the guests. Too complicate??

Thanks in advance!
________________________________
De : Cosmin ***@***.***>
Envoyé : Friday, March 31, 2023 10:30:44 AM
À : kcsoft/virtual-keys ***@***.***>
Cc : ouranos6 ***@***.***>; Author ***@***.***>
Objet : Re: [kcsoft/virtual-keys] No copy code (Issue #2)


Yes, it looks like you have to serve the page from a secure domain (https). Or disable that in chrome flags.
See the accepted answer here: https://stackoverflow.com/questions/51805395/navigator-clipboard-is-undefined

**Comment by kcsoft** [comment]
@ouranos6 I made a small update, so the key name in the list is a link so you can right click on it and copy the login url.
![image](https://user-images.githubusercontent.com/176441/231145180-13e58d0c-1cc9-4148-ae4a-56bdc64cfcbc.png)

**Comment by ouranos6** [comment]
Hello,

I've managed to do the same thing and add another nice feature like generate a QR-code to directly share with the guests.

Now I'am struggling to implement something. I want to pass the values for the time name and user via the url
`http://IP_HASSIO:8123/virtual-keys?name=hello&minutes=60&user=01a09ebff91e4c84a8a1c6c959b21942`

I can show the informations on the console log but I'am not able to have them populate the fields nor directly generate a new key.

Do you mind help me?

**Comment by kcsoft** [comment]
initial issue has been fixed, closing. Please create a new feature request
